# Site settings
title: Tim
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tmzhang.com" # the base hostname & protocol for your site

# Build settings
#markdown: kramdown
permalink: /:year/:month/:title.html   
paginate: 10                                
author:                                     #自定义常亮
  name: Tim
title: Tim                             #自定义常量

# avatar头像及Favicon
avatar: https://github.com/TmFeiouna/TmFeiouna.github.io/blob/master/iiimage/avatar_500.jpg

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量

markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

#ba:
 # src: //hm.baidu.com/hm.js?xxxxxxxx

# disqus 设置
#disqus:
  #shortname: coolnameismy